### ISSUE TITLE
[Umbrella] Migrate to Hooks

### ISSUE THREAD

**Issue by TejasQ** [contiamo/operational-ui#910]
[React Hooks has been merged](https://github.com/facebook/react/pull/14679) and so it's time to rewrite our entire library in hooks to:

1. Be cool, but also
1. To more effectively reuse stateful logic between our components, and most importantly, to
1. Be **extra `1337`**.

There are 18 components that use class components and need to be migrated. Let this issue serve as an umbrella to port them over. **Open separate issues if needed** and update the checklist to include a link to the issue, instead of just plain text.

## Components to Migrate

- [ ] [Autocomplete](https://github.com/contiamo/operational-ui/blob/master/src/Autocomplete/Autocomplete.tsx)
- [ ] [ContextMenu](https://github.com/contiamo/operational-ui/blob/master/src/ContextMenu/ContextMenu.tsx)
- [ ] [DatePicker](https://github.com/contiamo/operational-ui/blob/master/src/DatePicker/DatePicker.tsx)
- [ ] [Debug](https://github.com/contiamo/operational-ui/blob/master/src/Debug/Debug.tsx)
- [ ] [Foldable](https://github.com/contiamo/operational-ui/blob/master/src/Foldable/Foldable.tsx)
- [ ] [OperationalUI](https://github.com/contiamo/operational-ui/blob/master/src/OperationalUI/OperationalUI.tsx)
- [ ] [Page](https://github.com/contiamo/operational-ui/blob/master/src/Page/Page.tsx)
- [ ] [Select](https://github.com/contiamo/operational-ui/blob/master/src/Select/Select.tsx)
- [ ] [Splash](https://github.com/contiamo/operational-ui/blob/master/src/Splash/Splash.tsx)
- [ ] [Textarea](https://github.com/contiamo/operational-ui/blob/master/src/Textarea/Textarea.tsx)
- [ ] [Tooltip](https://github.com/contiamo/operational-ui/blob/master/src/Tooltip/Tooltip.tsx)
- [ ] [TopbarSelect](https://github.com/contiamo/operational-ui/blob/master/src/TopbarSelect/TopbarSelect.tsx)
- [ ] [Tree](https://github.com/contiamo/operational-ui/blob/master/src/Tree/Tree.tsx)

### Internal Components
- [ ] [Confirm](https://github.com/contiamo/operational-ui/blob/master/src/Internals/Confirm.tsx)
- [ ] [Modal](https://github.com/contiamo/operational-ui/blob/master/src/Internals/Modal.tsx)
- [ ] [Tabs](https://github.com/contiamo/operational-ui/blob/master/src/Internals/Tabs.tsx)

### Internal Utilities
- [ ] [deprecate](https://github.com/contiamo/operational-ui/blob/master/src/utils/deprecate.tsx)
- [ ] [StyleGuideRenderer](https://github.com/contiamo/operational-ui/blob/master/styleguide/StyleGuideRenderer.tsx)

**Comment by adeelibr** [comment]
Can I take `Foldable` up next? @TejasQ @fabien0102

**Comment by fabien0102** [comment]
@adeelibr You can! 💯

**Comment by JoshRosenstein** [comment]
Hey guys- great library. 
Im just surfing around trying to sharpen my TS & react skills. I glanced at tooltip to see if i could tackle it and looks like @fabien0102 put some work on it. But I wanted to ask if useLayoutEffect would be better for measurement hooks?

**Comment by TejasQ** [comment]
@JoshRosenstein, thanks for your amazing contributions! 🎉  How would Tooltip look with `useLayoutEffect`? I'm not really seeing the need for synchronicity there?

**Comment by fabien0102** [comment]
@JoshRosenstein I would like to refactor this component since a long time (but time… you know 😅 ). `useLayoutEffect` fit perfectly in this use case, so if you want to play with, be my guest! 🎉
Since we need to wait for the dom to calculate the size of the tooltip, it's perfect!
